# ===============================
# = PARAMETERS
# ===============================

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa

  jpa:
    database: h2
    show-sql: true

    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2

  data:
    rest:
      basePath: /api

logging:
  level:
    root: INFO

  file:
    name: ${user.home}/temp/application.log

server:
  port: 8080