# ===============================
# = PARAMETERS
# ===============================

# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    # URL para Windows (descomentada y lista para XAMPP)
    url: jdbc:mysql://localhost:3306/PETCLINIC_DB?useSSL=false&serverTimezone=UTC
    username: root
    password: 

  # CAMBIO AQUÍ: Desactivamos el script que causaba el BUILD FAILURE
  sql:
    init:
      mode: never

  # CAMBIO AQUÍ: Esto hace que Spring cree o actualice las tablas automáticamente en XAMPP
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      basePath: /api

logging:
  level:
    root: INFO
  file:
    name: ${user.home}/temp/application.log

server:
  port: 8080